### ISSUE TITLE
Not able to Ping the Same Destination with different Parameters Like Packet size,

### ISSUE THREAD

**Issue by Nachtfalkeaw** [SuperQ/smokeping_prober#130]
Hello,

If i configure the Same Destination two time but one time with size 64 and second time with 512 the /metrics Page throws an Error that Labels already exist.

```
targets:
- hosts:
  - 192.168.10.1
  (...)
  size: 64

- hosts:
  - 192.168.10.1
(...)
  size: 512 
```
