### ISSUE TITLE
Latency going up as more hosts are added

### ISSUE THREAD

**Issue by modena01** [SuperQ/smokeping_prober#156]
Thanks for smokeping! I am a prometheus newb, so please bear with me. Smokeping was working fine for me at first with a single host, then I tried adding about 100 additional hosts to ping, and the reported ICMP latency went up significantly. I dropped back down to 21 hosts, and latency dropped, but not back to the same level as with 1 target host.
is it correct config to have

```
targets:
 - hosts:
  - my.one.host
  - my.two.host
 - hosts:
  - my.three.host
```
Is the purpose of different (multiple) "hosts" section merely to have different variables such as interval and size, for different hosts? 
If smokeping is creating and tracking and reporting buckets to prometheus, is there a valid reason to scrape smokeping from prometheus any more often than say 1min?

My prometheus config is as yet very simple:
```
- job_name: 'smokeping_prober'
   scrape_interval: 60s
   static_configs:
   - targets: ['localhost:9374']
```
From the prometheus log, I see a message like this when I have a single ICMP target:
"Waiting 1s between starting pingers" 

but with 21 targets I get "Waiting 47.619047ms between starting pingers" so it is clearly dividing the number of targets into 1000ms, but I cannot find this in the smokeping code, so I guess it is prometheus doing this? I was looking at this trying to figure out why reported latency is going up higher and higher the more ICMP target hosts I add.

Thanks for your help.
