### ISSUE TITLE
Add smokeping job in prometheus.yml

### ISSUE THREAD

**Issue by freedomwarrior** [SuperQ/smokeping_prober#34]
Hello.
Can you show me example how can I add a correct job in prometheus.yml?
Thank you.

**Comment by paulfantom** [comment]
It is the same as any other service exposing metrics. For example I am using:
```yaml
- job_name: 'smokeping'
  static_configs:
  - targets:
    - '<<DNS_NAME_REDACTED>>:9374'
```
