### ISSUE TITLE
Dynamically add hosts

### ISSUE THREAD

**Issue by freedomwarrior** [SuperQ/smokeping_prober#37]
Ss it possible to add host  from file like `hosts.yml` or something? Or  only way is command args?

**Comment by SuperQ** [comment]
Currently on the command line. I have some ideas to add a yaml config with additional options per target. But it's only an idea at this point.

**Comment by xuanyuanaosheng** [comment]
@SuperQ  @freedomwarrior   May be this is a good solution: https://github.com/google/cloudprober

**Comment by cleonello** [comment]
+1
This really is a requirement for me to use smokeping_prober in a production environment.

**Comment by SuperQ** [comment]
@cleonello care to take a shot at adding the feature?

**Comment by cleonello** [comment]
@SuperQ, Sorry didn't see your reply.  I unfortunately don't know go.  I found a reasonable work around (for my deployments) for this issue, however.  I specify an environment configuration file where I define the hosts to scrape which is then read in by my systemd smokeping_prober service.   I do have to restart the service when the config is updated but it is suitable for my purposes.

For me to implement in production I still need to address issue  #35.   I need to add a custom label to my metrics in addition to IP address.  We identify monitored equipment by unique ID's, not by IP address.

**Comment by freedomwarrior** [comment]
> @SuperQ, Sorry didn't see your reply. I unfortunately don't know go. I found a reasonable work around (for my deployments) for this issue, however. I specify an environment configuration file where I define the hosts to scrape which is then read in by my systemd smokeping_prober service. I do have to restart the service when the config is updated but it is suitable for my purposes.
> 
> For me to implement in production I still need to address issue #35. I need to add a custom label to my metrics in addition to IP address. We identify monitored equipment by unique ID's, not by IP address.

Hi!
That's how you do it? 

```
EnvironmentFile=/etc/.progconf
ExecStart = /usr/bin/prog $ARG1 $ARG2
```

**Comment by edgarasg** [comment]
Would be great to have Consul support.

**Comment by paulfantom** [comment]
@SuperQ what about adding hosts/config in a similar way as it is done in blackbox-exporter? This way [the existing Prober mechanism from prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#probe) could be re-used to include smokeping_prober as another type of prober.

**Comment by SuperQ** [comment]
@paulfantom My current idea is something like this:

```yaml
targets:
- host: foo.example.com
  network: ip4
  protocol: icmp
  labels:
    name: Loadbalancer VIP1 DC1 v4
- host: foo.example.com
  network: ip6
  protocol: udp
  labels:
    name: Loadbalancer VIP1 DC1 v6
- host: 10.0.0.1
  network: ip # Automatic ip4/ip6
  # protocol: icmp # Defaults to ICMP
```

The blackbox-exporter takes the discovery from the Prometheus side via `target` param. This exporter has it's own discovery.
