### ISSUE TITLE
Dashboard for hostnames with IPv4 and IPv6

### ISSUE THREAD

**Issue by strayer** [SuperQ/smokeping_prober#90]
Thanks for building this and providing a dashboard!

I'm trying to monitor both IPv4 and IPv6 pings to Hetzner datacenters:

```
---
targets:
- hosts:
  - fsn.icmp.hetzner.com
  - nbg.icmp.hetzner.com
  - hel.icmp.hetzner.com
  network: ip4
  protocol: icmp
- hosts:
  - fsn.icmp.hetzner.com
  - nbg.icmp.hetzner.com
  - hel.icmp.hetzner.com
  network: ip6
  protocol: icmp
```

This seems to work fine in general, but the dashboard included in this repository seems to mix up the hosts in the graphs:

<img width="1067" alt="grafik" src="https://user-images.githubusercontent.com/310624/216719483-1c647e9f-77f0-4122-a05a-0b31e3c9f54a.png">

While the latency and packet loss graph can be easily extended to have `{{ip}}` in their labels I'm not quite sure how this could be done with the Smoke Ping graph, as it sums up the buckets. The packet loss graph also has some issues with the override when changing the `Count` label.

I don't have much experience with more complex graphs in Grafana and Prometheus, so any guidance would be appreciated!
